# -*- coding: utf-8 -*-

from Qt import (
    QtWidgets,
    QtCore,
    QtGui
)





class Widget (object):

    def setupUi(self, ExportUI, ListViewLayout):

        ExportUI.setObjectName("ExportUI")
        ExportUI.resize(755, 528)

        ExportUI.setProperty("background", "options")
        ExportUI.setProperty("border", "none")

        self.verticalLayout = QtWidgets.QVBoxLayout(ExportUI)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainLayout = QtWidgets.QHBoxLayout()
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.mainLayout.addItem(ListViewLayout)

        self.optionLayout = QtWidgets.QVBoxLayout()
        self.optionLayout.setContentsMargins(30, 0, 30, 30)
        self.optionLayout.setSpacing(0)
        self.optionLayout.setObjectName("optionLayout")
        self.nameLayout = QtWidgets.QHBoxLayout()
        self.nameLayout.setContentsMargins(0, 16, 0, 30)
        self.nameLayout.setSpacing(0)
        self.nameLayout.setObjectName("nameLayout")
        self.nameLineEdit = QtWidgets.QLineEdit(ExportUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameLineEdit.sizePolicy().hasHeightForWidth())
        self.nameLineEdit.setSizePolicy(sizePolicy)
        self.nameLineEdit.setMinimumSize(QtCore.QSize(0, 32))
        self.nameLineEdit.setMaximumSize(QtCore.QSize(16777215, 32))
        self.nameLineEdit.setSizeIncrement(QtCore.QSize(0, 0))
        self.nameLineEdit.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.nameLineEdit.setProperty("background", "input")
        self.nameLineEdit.setProperty("border", "none")
        self.nameLineEdit.setProperty("border", "round")
        self.nameLineEdit.setProperty("textcolor", "light")
        self.nameLineEdit.setTextMargins(10, 0, 0, 0)
        self.nameLayout.addWidget(self.nameLineEdit)

        self.optionLayout.addLayout(self.nameLayout)
        self.modelingLayout = QtWidgets.QHBoxLayout()
        self.modelingLayout.setContentsMargins(0, 0, 0, 4)
        self.modelingLayout.setSpacing(10)
        self.modelingLayout.setObjectName("modelingLayout")
        self.modelingLabel = QtWidgets.QLabel(ExportUI)
        self.modelingLabel.setMinimumSize(QtCore.QSize(55, 18))
        self.modelingLabel.setMaximumSize(QtCore.QSize(55, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.modelingLabel.setFont(font)
        self.modelingLabel.setObjectName("modelingLabel")
        self.modelingLabel.setProperty("textcolor", "light")
        self.modelingLayout.addWidget(self.modelingLabel)

        self.modelingSwitch = QtWidgets.QPushButton(ExportUI)
        self.modelingSwitch.setMinimumSize(QtCore.QSize(16, 16))
        self.modelingSwitch.setMaximumSize(QtCore.QSize(16, 16))
        self.modelingSwitch.setText("")
        self.modelingSwitch.setCheckable(True)
        self.modelingSwitch.setFlat(True)
        self.modelingSwitch.setObjectName("modelingSwitch")
        self.modelingLayout.addWidget(self.modelingSwitch)
        self.modelingOverwrite = QtWidgets.QPushButton(ExportUI)
        self.modelingOverwrite.setMinimumSize(QtCore.QSize(50, 16))
        self.modelingOverwrite.setMaximumSize(QtCore.QSize(50, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.modelingOverwrite.setFont(font)
        self.modelingOverwrite.setCheckable(True)
        self.modelingOverwrite.setObjectName("modelingOverwrite")
        self.modelingLayout.addWidget(self.modelingOverwrite)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.modelingLayout.addItem(spacerItem)
        self.optionLayout.addLayout(self.modelingLayout)
        self.surfacingLayout = QtWidgets.QHBoxLayout()
        self.surfacingLayout.setContentsMargins(0, 0, 0, 0)
        self.surfacingLayout.setSpacing(10)
        self.surfacingLayout.setObjectName("surfacingLayout")
        self.surfacingLabel = QtWidgets.QLabel(ExportUI)
        self.surfacingLabel.setMinimumSize(QtCore.QSize(55, 18))
        self.surfacingLabel.setMaximumSize(QtCore.QSize(55, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.surfacingLabel.setFont(font)
        self.surfacingLabel.setObjectName("surfacingLabel")
        self.surfacingLabel.setProperty("textcolor", "light")
        self.surfacingLayout.addWidget(self.surfacingLabel)

        self.surfacingSwitch = QtWidgets.QPushButton(ExportUI)
        self.surfacingSwitch.setMinimumSize(QtCore.QSize(16, 16))
        self.surfacingSwitch.setMaximumSize(QtCore.QSize(16, 16))
        self.surfacingSwitch.setText("")
        self.surfacingSwitch.setCheckable(True)
        self.surfacingSwitch.setObjectName("surfacingSwitch")
        self.surfacingLayout.addWidget(self.surfacingSwitch)

        self.surfacingOverwrite = QtWidgets.QPushButton(ExportUI)
        self.surfacingOverwrite.setMinimumSize(QtCore.QSize(50, 16))
        self.surfacingOverwrite.setMaximumSize(QtCore.QSize(50, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.surfacingOverwrite.setFont(font)
        self.surfacingOverwrite.setCheckable(True)
        self.surfacingOverwrite.setFlat(True)
        self.surfacingOverwrite.setObjectName("surfacingOverwrite")
        self.surfacingLayout.addWidget(self.surfacingOverwrite)

        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.surfacingLayout.addItem(spacerItem1)
        self.optionLayout.addLayout(self.surfacingLayout)

        self.animationLayout = QtWidgets.QHBoxLayout()
        self.animationLayout.setContentsMargins(0, 20, 0, 4)
        self.animationLayout.setSpacing(10)
        self.animationLayout.setObjectName("animationLayout")
        self.animationLabel = QtWidgets.QLabel(ExportUI)
        self.animationLabel.setMinimumSize(QtCore.QSize(55, 18))
        self.animationLabel.setMaximumSize(QtCore.QSize(55, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.animationLabel.setFont(font)
        self.animationLabel.setObjectName("animationLabel")
        self.animationLabel.setProperty("textcolor", "light")
        self.animationLayout.addWidget(self.animationLabel)

        self.animationSwitch = QtWidgets.QPushButton(ExportUI)
        self.animationSwitch.setMinimumSize(QtCore.QSize(16, 16))
        self.animationSwitch.setMaximumSize(QtCore.QSize(16, 16))
        self.animationSwitch.setText("")
        self.animationSwitch.setCheckable(True)
        self.animationSwitch.setFlat(True)
        self.animationSwitch.setObjectName("animationSwitch")
        self.animationLayout.addWidget(self.animationSwitch)

        self.animationOverwrite = QtWidgets.QPushButton(ExportUI)
        self.animationOverwrite.setMinimumSize(QtCore.QSize(50, 16))
        self.animationOverwrite.setMaximumSize(QtCore.QSize(50, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.animationOverwrite.setFont(font)
        self.animationOverwrite.setCheckable(True)
        self.animationOverwrite.setFlat(True)
        self.animationOverwrite.setObjectName("animationOverwrite")
        self.animationLayout.addWidget(self.animationOverwrite)

        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.animationLayout.addItem(spacerItem2)
        self.optionLayout.addLayout(self.animationLayout)

        self.animationNameLayout = QtWidgets.QHBoxLayout()
        self.animationNameLayout.setContentsMargins(-1, 0, -1, 0)
        self.animationNameLayout.setSpacing(10)
        self.animationNameLayout.setObjectName("animationNameLayout")
        self.animationNameLabel = QtWidgets.QLabel(ExportUI)
        self.animationNameLabel.setMinimumSize(QtCore.QSize(55, 24))
        self.animationNameLabel.setMaximumSize(QtCore.QSize(55, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.animationNameLabel.setFont(font)
        self.animationNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.animationNameLabel.setObjectName("animationNameLabel")
        self.animationNameLabel.setProperty("textcolor", "light")
        self.animationNameLayout.addWidget(self.animationNameLabel)

        self.animationNameCombobox = QtWidgets.QComboBox(ExportUI)
        self.animationNameCombobox.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.animationNameCombobox.setFont(font)
        self.animationNameCombobox.setToolTip("")
        self.animationNameCombobox.setStatusTip("")
        self.animationNameCombobox.setWhatsThis("")
        self.animationNameCombobox.setAccessibleName("")
        self.animationNameCombobox.setAccessibleDescription("")
        self.animationNameCombobox.setEditable(True)
        self.animationNameCombobox.setCurrentText("animation")
        self.animationNameCombobox.setMaxVisibleItems(10)
        self.animationNameCombobox.setMaxCount(100)
        self.animationNameCombobox.setFrame(False)
        self.animationNameCombobox.setObjectName("animationNameCombobox")
        self.animationNameCombobox.addItem("")
        self.animationNameCombobox.addItem("")
        self.animationNameCombobox.addItem("")
        self.animationNameLayout.addWidget(self.animationNameCombobox)

        self.optionLayout.addLayout(self.animationNameLayout)

        self.animationRangeLayout = QtWidgets.QHBoxLayout()
        self.animationRangeLayout.setContentsMargins(0, 0, 0, 0)
        self.animationRangeLayout.setSpacing(10)
        self.animationRangeLayout.setObjectName("animationRangeLayout")
        self.animationRangeLabel = QtWidgets.QLabel(ExportUI)
        self.animationRangeLabel.setMinimumSize(QtCore.QSize(55, 24))
        self.animationRangeLabel.setMaximumSize(QtCore.QSize(55, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.animationRangeLabel.setFont(font)
        self.animationRangeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.animationRangeLabel.setObjectName("animationRangeLabel")
        self.animationRangeLabel.setProperty("textcolor", "light")
        self.animationRangeLayout.addWidget(self.animationRangeLabel)

        self.rangeGroupLayout = QtWidgets.QHBoxLayout()
        self.rangeGroupLayout.setSpacing(2)
        self.rangeGroupLayout.setObjectName("rangeGroupLayout")
        self.rangeFromSpinbox = QtWidgets.QSpinBox(ExportUI)
        self.rangeFromSpinbox.setMinimumSize(QtCore.QSize(50, 18))
        self.rangeFromSpinbox.setMaximumSize(QtCore.QSize(50, 18))
        self.rangeFromSpinbox.setMinimum(0)
        self.rangeFromSpinbox.setMaximum(99999)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rangeFromSpinbox.setFont(font)
        self.rangeFromSpinbox.setToolTip("")
        self.rangeFromSpinbox.setStatusTip("")
        self.rangeFromSpinbox.setWhatsThis("")
        self.rangeFromSpinbox.setAccessibleName("")
        self.rangeFromSpinbox.setAccessibleDescription("")
        self.rangeFromSpinbox.setWrapping(False)
        self.rangeFromSpinbox.setFrame(True)
        self.rangeFromSpinbox.setReadOnly(False)
        self.rangeFromSpinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.rangeFromSpinbox.setSpecialValueText("")
        self.rangeFromSpinbox.setSuffix("")
        self.rangeFromSpinbox.setPrefix("")
        self.rangeFromSpinbox.setProperty("value", 1)
        self.rangeFromSpinbox.setObjectName("rangeFromSpinbox")
        self.rangeFromSpinbox.setProperty("background", "input")
        self.rangeFromSpinbox.setProperty("border", "none")
        self.rangeFromSpinbox.setProperty("textcolor", "light")
        self.rangeGroupLayout.addWidget(self.rangeFromSpinbox)

        self.rangeToSpinbox = QtWidgets.QSpinBox(ExportUI)
        self.rangeToSpinbox.setMinimumSize(QtCore.QSize(50, 18))
        self.rangeToSpinbox.setMaximumSize(QtCore.QSize(50, 18))
        self.rangeToSpinbox.setMinimum(0)
        self.rangeToSpinbox.setMaximum(99999)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rangeToSpinbox.setFont(font)
        self.rangeToSpinbox.setToolTip("")
        self.rangeToSpinbox.setStatusTip("")
        self.rangeToSpinbox.setWhatsThis("")
        self.rangeToSpinbox.setAccessibleName("")
        self.rangeToSpinbox.setAccessibleDescription("")
        self.rangeToSpinbox.setWrapping(False)
        self.rangeToSpinbox.setFrame(True)
        self.rangeToSpinbox.setReadOnly(False)
        self.rangeToSpinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.rangeToSpinbox.setSpecialValueText("")
        self.rangeToSpinbox.setSuffix("")
        self.rangeToSpinbox.setPrefix("")
        self.rangeToSpinbox.setProperty("value", 1)
        self.rangeToSpinbox.setObjectName("rangeToSpinbox")
        self.rangeToSpinbox.setProperty("background", "input")
        self.rangeToSpinbox.setProperty("border", "none")
        self.rangeToSpinbox.setProperty("textcolor", "light")
        self.rangeGroupLayout.addWidget(self.rangeToSpinbox)

        rangeSpacer = QtWidgets.QSpacerItem(6, 6, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.rangeGroupLayout.addItem(rangeSpacer)
        self.rangeButton = QtWidgets.QPushButton(ExportUI)
        self.rangeButton.setMinimumSize(QtCore.QSize(36, 18))
        self.rangeButton.setMaximumSize(QtCore.QSize(36, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rangeButton.setFont(font)
        self.rangeButton.setFlat(False)
        self.rangeButton.setObjectName("rangeButton")
        self.rangeGroupLayout.addWidget(self.rangeButton)

        self.animationRangeLayout.addLayout(self.rangeGroupLayout)
        self.optionLayout.addLayout(self.animationRangeLayout)

        self.fpsLayout = QtWidgets.QHBoxLayout()
        self.fpsLayout.setContentsMargins(-1, 0, -1, 0)
        self.fpsLayout.setSpacing(10)
        self.fpsLayout.setObjectName("fpsLayout")
        self.fpsLabel = QtWidgets.QLabel(ExportUI)
        self.fpsLabel.setMinimumSize(QtCore.QSize(55, 24))
        self.fpsLabel.setMaximumSize(QtCore.QSize(55, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.fpsLabel.setFont(font)
        self.fpsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fpsLabel.setObjectName("fpsLabel")
        self.fpsLabel.setProperty("textcolor", "light")
        self.fpsLayout.addWidget(self.fpsLabel)

        self.fpsSpinbox = QtWidgets.QSpinBox(ExportUI)
        self.fpsSpinbox.setMaximumSize(QtCore.QSize(50, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.fpsSpinbox.setFont(font)
        self.fpsSpinbox.setToolTip("")
        self.fpsSpinbox.setStatusTip("")
        self.fpsSpinbox.setWhatsThis("")
        self.fpsSpinbox.setAccessibleName("")
        self.fpsSpinbox.setAccessibleDescription("")
        self.fpsSpinbox.setWrapping(False)
        self.fpsSpinbox.setFrame(True)
        self.fpsSpinbox.setReadOnly(False)
        self.fpsSpinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.fpsSpinbox.setSpecialValueText("")
        self.fpsSpinbox.setSuffix("")
        self.fpsSpinbox.setPrefix("")
        self.fpsSpinbox.setProperty("value", 30)
        self.fpsSpinbox.setObjectName("fpsSpinbox")
        self.fpsSpinbox.setProperty("background", "options")
        self.fpsSpinbox.setProperty("border", "none")
        self.fpsSpinbox.setProperty("textcolor", "light")
        self.fpsLayout.addWidget(self.fpsSpinbox)

        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.fpsLayout.addItem(spacerItem4)
        self.optionLayout.addLayout(self.fpsLayout)

        self.variantLayout = QtWidgets.QHBoxLayout()
        self.variantLayout.setContentsMargins(-1, 40, -1, 0)
        self.variantLayout.setSpacing(10)
        self.variantLayout.setObjectName("variantLayout")
        self.variantLabel = QtWidgets.QLabel(ExportUI)
        self.variantLabel.setMinimumSize(QtCore.QSize(55, 24))
        self.variantLabel.setMaximumSize(QtCore.QSize(55, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.variantLabel.setFont(font)
        self.variantLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.variantLabel.setObjectName("variantLabel")
        self.variantLabel.setProperty("textcolor", "light")
        self.variantLayout.addWidget(self.variantLabel)

        self.variantCombobox = QtWidgets.QComboBox(ExportUI)
        self.variantCombobox.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.variantCombobox.setFont(font)
        self.variantCombobox.setToolTip("")
        self.variantCombobox.setStatusTip("")
        self.variantCombobox.setWhatsThis("")
        self.variantCombobox.setAccessibleName("")
        self.variantCombobox.setAccessibleDescription("")
        self.variantCombobox.setEditable(True)
        self.variantCombobox.setCurrentText("")
        self.variantCombobox.setMaxVisibleItems(10)
        self.variantCombobox.setMaxCount(100)
        self.variantCombobox.setFrame(False)
        self.variantCombobox.setObjectName("variantCombobox")
        self.variantCombobox.addItem("")
        self.variantCombobox.addItem("")
        self.variantCombobox.setProperty("textcolor", "light")
        self.variantLayout.addWidget(self.variantCombobox)

        self.optionLayout.addLayout(self.variantLayout)
        self.versionLayout = QtWidgets.QHBoxLayout()
        self.versionLayout.setContentsMargins(0, 0, 0, 0)
        self.versionLayout.setSpacing(10)
        self.versionLayout.setObjectName("versionLayout")

        self.versionLabel = QtWidgets.QLabel(ExportUI)
        self.versionLabel.setMinimumSize(QtCore.QSize(55, 24))
        self.versionLabel.setMaximumSize(QtCore.QSize(55, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.versionLabel.setFont(font)
        self.versionLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.versionLabel.setObjectName("versionLabel")
        self.versionLabel.setProperty("textcolor", "light")
        self.versionLayout.addWidget(self.versionLabel)

        self.finalLayout = QtWidgets.QHBoxLayout()
        self.finalLayout.setContentsMargins(0, 0, 0, 0)
        self.finalLayout.setSpacing(0)
        self.finalLayout.setObjectName("finalLayout")
        self.versionLayout.addLayout(self.finalLayout)

        self.versionCombobox = QtWidgets.QComboBox(ExportUI)
        self.versionCombobox.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.versionCombobox.setFont(font)
        self.versionCombobox.setToolTip("")
        self.versionCombobox.setStatusTip("")
        self.versionCombobox.setWhatsThis("")
        self.versionCombobox.setAccessibleName("")
        self.versionCombobox.setAccessibleDescription("")
        self.versionCombobox.setEditable(True)
        self.versionCombobox.setCurrentText("")
        self.versionCombobox.setMaxVisibleItems(10)
        self.versionCombobox.setMaxCount(100)
        self.versionCombobox.setFrame(False)
        self.versionCombobox.setObjectName("versionCombobox")
        self.versionCombobox.addItem("")
        self.versionCombobox.addItem("")
        self.versionCombobox.addItem("")
        self.versionCombobox.addItem("")
        self.finalLayout.addWidget(self.versionCombobox)

        self.finalButton = QtWidgets.QPushButton(ExportUI)
        self.finalButton.setMinimumSize(QtCore.QSize(36, 18))
        self.finalButton.setMaximumSize(QtCore.QSize(36, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.finalButton.setFont(font)
        self.finalButton.setCheckable(True)
        self.finalButton.setFlat(True)
        self.finalButton.setObjectName("finalButton")
        self.finalLayout.addWidget(self.finalButton)

        self.optionLayout.addLayout(self.versionLayout)

        self.unitGroupLayout = QtWidgets.QHBoxLayout()
        self.unitGroupLayout.setContentsMargins(-1, 20, -1, 0)
        self.unitGroupLayout.setSpacing(10)
        self.unitGroupLayout.setObjectName("unitGroupLayout")
        self.unitGroupLabel = QtWidgets.QLabel(ExportUI)
        self.unitGroupLabel.setMinimumSize(QtCore.QSize(55, 24))
        self.unitGroupLabel.setMaximumSize(QtCore.QSize(55, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.unitGroupLabel.setFont(font)
        self.unitGroupLabel.setText("")
        self.unitGroupLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unitGroupLabel.setObjectName("unitGroupLabel")
        self.unitGroupLayout.addWidget(self.unitGroupLabel)

        self.unitLayout = QtWidgets.QHBoxLayout()
        self.unitLayout.setContentsMargins(-1, 0, -1, 0)
        self.unitLayout.setSpacing(10)
        self.unitLayout.setObjectName("unitLayout")
        self.unitLabel = QtWidgets.QLabel(ExportUI)
        self.unitLabel.setMinimumSize(QtCore.QSize(55, 24))
        self.unitLabel.setMaximumSize(QtCore.QSize(200, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.unitLabel.setFont(font)
        self.unitLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.unitLabel.setObjectName("unitLabel")
        self.unitLabel.setProperty("textcolor", "light")
        self.unitLayout.addWidget(self.unitLabel)

        self.unitSpinbox = QtWidgets.QDoubleSpinBox(ExportUI)
        self.unitSpinbox.setMinimumSize(QtCore.QSize(50, 18))
        self.unitSpinbox.setMaximumSize(QtCore.QSize(50, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.unitSpinbox.setFont(font)
        self.unitSpinbox.setToolTip("")
        self.unitSpinbox.setStatusTip("")
        self.unitSpinbox.setWhatsThis("")
        self.unitSpinbox.setAccessibleName("")
        self.unitSpinbox.setAccessibleDescription("")
        self.unitSpinbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.unitSpinbox.setWrapping(False)
        self.unitSpinbox.setFrame(True)
        self.unitSpinbox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unitSpinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.unitSpinbox.setSpecialValueText("")
        self.unitSpinbox.setAccelerated(False)
        self.unitSpinbox.setSuffix("")
        self.unitSpinbox.setDecimals(2)
        self.unitSpinbox.setMaximum(1000.0)
        self.unitSpinbox.setProperty("value", 1.0)
        self.unitSpinbox.setObjectName("unitSpinbox")
        self.unitSpinbox.setProperty("background", "options")
        self.unitSpinbox.setProperty("border", "none")
        self.unitSpinbox.setProperty("textcolor", "light")
        self.unitLayout.addWidget(self.unitSpinbox)

        self.unitGroupLayout.addLayout(self.unitLayout)
        self.optionLayout.addLayout(self.unitGroupLayout)

        spacerItem5 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.optionLayout.addItem(spacerItem5)

        self.exportLayout = QtWidgets.QHBoxLayout()
        self.exportLayout.setContentsMargins(0, 30, 0, 0)
        self.exportLayout.setSpacing(10)
        self.exportLayout.setObjectName("exportLayout")
        self.exportButton = QtWidgets.QPushButton(ExportUI)
        self.exportButton.setMinimumHeight(32)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.exportButton.setFont(font)
        self.exportButton.setFlat(True)
        self.exportButton.setObjectName("exportButton")
        self.exportLayout.addWidget(self.exportButton)

        self.optionLayout.addLayout(self.exportLayout)
        self.mainLayout.addLayout(self.optionLayout)

        self.mainLayout.setStretch(0, 1)
        self.verticalLayout.addLayout(self.mainLayout)

        ExportUI.setWindowTitle("Form")
        self.nameLineEdit.setText("Name")
        self.modelingLabel.setText("Modeling")
        self.modelingOverwrite.setText("overwrite")
        self.surfacingLabel.setText("Surfacing")
        self.surfacingOverwrite.setText("overwrite")
        self.animationLabel.setText("Animation")
        self.animationOverwrite.setText("overwrite")
        self.animationNameLabel.setText("name")
        self.animationNameCombobox.setItemText(0, "animation")
        self.animationNameCombobox.setItemText(1, "idle")
        self.animationNameCombobox.setItemText(2, "run")
        self.animationRangeLabel.setText("range")
        self.rangeButton.setText("get")
        self.fpsLabel.setText("fps")
        self.variantLabel.setText("Variant")
        self.variantCombobox.setItemText(0, "high")
        self.variantCombobox.setItemText(1, "low")
        self.versionLabel.setText("Version")
        self.versionCombobox.setItemText(0, "01")
        self.versionCombobox.setItemText(1, "02")
        self.versionCombobox.setItemText(2, "03")
        self.versionCombobox.setItemText(3, "04")
        self.finalButton.setText("final")
        self.unitLabel.setText("unit multiplier")
        self.exportButton.setText("Export")

        self.animationNameCombobox.setCurrentIndex(0)
        self.variantCombobox.setCurrentIndex(-1)
        self.versionCombobox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(ExportUI)









if __name__ == "__main__":


    class ExportWidget (QtWidgets.QWidget, Widget):

        def __init__ (self):
            super(ExportWidget, self).__init__()

            self.AssetBrowser = QtWidgets.QListView()
            self.assetLayout = QtWidgets.QVBoxLayout()
            self.assetLayout.addWidget(self.AssetBrowser)

            self.setupUi(self, self.assetLayout)


    application = QtWidgets.QApplication([])
    widget = ExportWidget()
    widget.show()
    application.exec_()
