#!/usr/bin/env bash
# Katana launcher script



# create required ASSET_MANAGER variable
# that contains this directory
THISDIR=$(dirname "$(readlink -e "$BASH_SOURCE")")
export ASSET_MANAGER=$THISDIR

export KATANA_RESOURCES=$KATANA_RESOURCES:$ASSET_MANAGER



# export KATANA_HOME=...
# exec "${KATANA_HOME}/bin/katanaBin" "$@"
